config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"

    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    resources :users do
      resources :microposts, only: %i(create destroy)
      member do
        get :following, :followers
      end
    end

    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"

    resources :account_activations, only: :edit

    resources :password_resets, except: %i(index show destroy)

    resources :relationships, only: %i(create destroy)

    resource :static_pages do
      collection do
        get "/home", to: "static_pages#home"
        get "/contact", to: "static_pages#contact"
        get "/help", to: "static_pages#help"
      end
    end
  end
end

app/views/layouts/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t (".form_contain"), er_count: pluralize(object.errors.count, t(".error")) %>
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%== pagy_bootstrap_nav(@pagy) %>
<% end %>

app/views/layouts/shared/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="nav navbar-nav navbar-left language">
    <%= link_to "en", locale: :en %> |
    <%= link_to "vi", locale: :vi %>
  </div>
  <div class="container">
    <%= link_to t(".logo"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t(".menu_home"), home_static_pages_path %></li>
        <li><%= link_to t(".menu_contact"), contact_static_pages_path %></li>
        <li><%= link_to t(".menu_help"), help_static_pages_path %></li>
        <li><%= link_to t(".menu_login"), "#" %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/shared/_micropost_form.html.erb
<%= form_for [@micropost.user, @micropost] do |f| %>
  <%= render "layouts/shared/error_messages", object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: t(".compose_micropost") %>
  </div>
  <%= f.submit t(".post_label"), class: "btn btn-primary" %>
  <span class="image">
    <%= f.file_field :image, accept: Settings.image.accept_image %>
  </span>
<% end %>
<%= javascript_pack_tag "micropost_image" %>

app/views/layouts/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <%= link_to following_user_path(@user) do %>
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    <%= t("following_title") %>
  <% end %>
  <%= link_to followers_user_path(@user) do %>
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    <%= t("follower_title") %>
  <% end %>
</div>

app/views/layouts/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: Settings.gravatar_size.size_50),
                                       current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to t(".view_profile"), current_user %></span>
<span><%= pluralize current_user.microposts.count, t(".micropost") %></span>